name: simple_animal_app
description: A simple Flutter application that toggles between displaying 'Cat' and 'Dog' text with respective icons when clicked.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  bloc_test: ^9.0.0
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true